/forward_camera/vloc_node:
  ros__parameters:
    # Localize, don't calibrate
    loc_calibrate_not_localize: 0

    # 0: OpenCV, 1: GTSAM
    loc_camera_sam_not_cv: 1

    # Use DICT_4x4_50
    loc_aruco_dictionary_id: 0

    # Do not publish tfs
    psl_publish_tfs: 0

    # Camera info is published reliable, not best-effort
    psl_sub_camera_info_best_effort_not_reliable: 0

    # Publish the camera pose, but nothing else
    psl_publish_camera_pose: 1
    psl_publish_base_pose: 0
    psl_publish_camera_odom: 0
    psl_publish_base_odom: 0

    # Keep the existing timestamps
    psl_stamp_msgs_with_current_time: 0

/auv_node:
  ros__parameters:
    param_fluid_density: 997.0

    # Timer is stable w/ or w/o filter:
    loop_driver: 0

    # filter_node is running:
    publish_tf: false

    # How far in front of a marker is a good pose?
    good_pose_dist: 2.0

    # Allow MTM recovery
    global_plan_allow_mtm: true

    # Do not allow waypoints
    pose_plan_waypoints: false

    # If xy distance is > this, then build a long plan (rotate, run, rotate)
    # Otherwise build a short plan (move in all DoF at once)
    pose_plan_max_short_plan_xy: 0.5

    # How close to the markers should we get?
    pose_plan_target_dist: 0.8
    mtm_plan_target_dist: 1.5

/filter_node:
  ros__parameters:
    param_fluid_density: 997.0
    predict_accel: false
    predict_accel_control: false
    predict_accel_drag: false
    predict_accel_buoyancy: false
    filter_baro: true
    filter_fcam: true
    publish_tf: true

    # How far in front of a marker is a good pose?
    good_pose_dist: 2.0
