mv marker_2_pad/materials/scripts/aruco_visual_marker_2_num.material     marker_2_pad/materials/scripts/marker_2_num.material    
mv marker_2_pad/materials/scripts/aruco_visual_marker_2_marker.material  marker_2_pad/materials/scripts/marker_2.material       
mv marker_7_pad/materials/scripts/aruco_visual_marker_7_marker.material  marker_7_pad/materials/scripts/marker_7.material   
mv marker_7_pad/materials/scripts/aruco_visual_marker_7_num.material     marker_7_pad/materials/scripts/marker_7_num.material    
mv marker_4_pad/materials/scripts/aruco_visual_marker_4_marker.material  marker_4_pad/materials/scripts/marker_4.material   
mv marker_4_pad/materials/scripts/aruco_visual_marker_4_num.material     marker_4_pad/materials/scripts/marker_4_num.material    
mv marker_1_pad/materials/scripts/aruco_visual_marker_1_marker.material  marker_1_pad/materials/scripts/marker_1.material   
mv marker_1_pad/materials/scripts/aruco_visual_marker_1_num.material     marker_1_pad/materials/scripts/marker_1_num.material    
mv marker_5/materials/scripts/aruco_visual_marker_5_marker.material      marker_5/materials/scripts/marker_5.material    
mv marker_1/materials/scripts/aruco_visual_marker_1_marker.material      marker_1/materials/scripts/marker_1.material    
mv marker_6_pad/materials/scripts/aruco_visual_marker_6_num.material     marker_6_pad/materials/scripts/marker_6_num.material    
mv marker_6_pad/materials/scripts/aruco_visual_marker_6_marker.material  marker_6_pad/materials/scripts/marker_6.material   
mv marker_6/materials/scripts/aruco_visual_marker_6_marker.material      marker_6/materials/scripts/marker_6.material    
mv marker_4/materials/scripts/aruco_visual_marker_4_marker.material      marker_4/materials/scripts/marker_4.material    
mv marker_0_pad/materials/scripts/aruco_visual_marker_0_marker.material  marker_0_pad/materials/scripts/marker_0.material   
mv marker_0_pad/materials/scripts/aruco_visual_marker_0_num.material     marker_0_pad/materials/scripts/marker_0_num.material    
mv marker_5_pad/materials/scripts/aruco_visual_marker_5_num.material     marker_5_pad/materials/scripts/marker_5_num.material    
mv marker_5_pad/materials/scripts/aruco_visual_marker_5_marker.material  marker_5_pad/materials/scripts/marker_5.material   
mv marker_3_pad/materials/scripts/aruco_visual_marker_3_num.material     marker_3_pad/materials/scripts/marker_3_num.material    
mv marker_3_pad/materials/scripts/aruco_visual_marker_3_marker.material  marker_3_pad/materials/scripts/marker_3.material   
mv marker_7/materials/scripts/aruco_visual_marker_7_marker.material      marker_7/materials/scripts/marker_7.material    
mv marker_2/materials/scripts/aruco_visual_marker_2_marker.material      marker_2/materials/scripts/marker_2.material    
mv marker_3/materials/scripts/aruco_visual_marker_3_marker.material      marker_3/materials/scripts/marker_3.material    
mv marker_0/materials/scripts/aruco_visual_marker_0_marker.material      marker_0/materials/scripts/marker_0.material    
