/forward_camera/vloc_node:
  ros__parameters:
    publish_tfs: 0
    publish_tfs_per_marker: 0
    sub_camera_info_best_effort_not_reliable: 1
    publish_camera_pose: 1
    publish_base_pose: 0
    publish_camera_odom: 0
    publish_base_odom: 0

    # I hacked up several sensor plugins in gazebo_ros_pkgs to publish everything in wall time,
    # so vloc_node doesn't need to overwrite the timestamps
    stamp_msgs_with_current_time: 0
