# Goal

# This will be copied to /control.mission.mission_info, useful for experiments
string mission_info

# Target type
uint16 TARGET_MARKER=0    # Markers in marker_ids[]
uint16 TARGET_POSE=1      # Poses in poses[]
uint16 TARGET_MOTION=2    # Motions in motions[]
uint16 target_type

# List of target markers, if empty visit all markers on the map
int32[] marker_ids

# List of target poses, if empty use the current pose
geometry_msgs/Pose[] poses

# List of motions, relative to the current pose, additive
orca_msgs/PoseBody[] motions

# Randomize the list of targets
bool random false

# Keep station at the last target
bool keep_station false

######
# EXAMPLES
#
# To visit all of the markers in the map in a random pattern:
#     random = true
#
# To visit markers 0, 1 and 3 in order:
#     marker_ids = [0, 1, 2]
#
# To keep station at the current pose:
#     target_type = 1
#     keep_station = true
######

---

# Result

int16 targets_completed
int16 targets_total

---

# Feedback

int16 targets_completed
int16 targets_total
