# Goal, see constants in Control.msg for mode

uint8 mode

geometry_msgs/Pose[] poses

---

# Result

int16 targets_completed
int16 targets_total

---

# Feedback

int16 targets_completed
int16 targets_total
